### ISSUE TITLE
Docs are still from 2 days ago

### ISSUE THREAD

**Issue by fire** [iree-gd/iree.gd.docs#4]
Docs aren't updating @RechieKho

**Comment by RechieKho** [comment]
You need to use mkdocs gh-deploy

**Comment by fire** [comment]
I don't have access, and it breaks the single action rule of CICD.

**Comment by RechieKho** [comment]
So we couldn't set up CI/CD for it? I see that one would need to setup git in the CI/CD first from this [website](https://squidfunk.github.io/mkdocs-material/publishing-your-site/)

**Comment by fire** [comment]
I made a pull request https://github.com/iree-gd/iree.gd.docs/pull/5

**Comment by fire** [comment]
https://github.com/iree-gd/iree.gd.docs/pull/5 was merged. closing
